python main.py --numpy_seed 10 --torch_seed 10 --n_meta_agent_learning_cycles 200 --max_t 10 --n_agents_learning_cycles 10 --actor_lr 0.0015 --meta_lr 0.003 --thresholds 15 15 15 --environment ExploreContinuous --shuffle --algo ac --coarseness 6 --unconstrained
python main.py --numpy_seed 11 --torch_seed 11 --n_meta_agent_learning_cycles 40 --n_agents_learning_cycles 30 --actor_lr 0.0015 --meta_lr 0.003 --thresholds 15 15 15 --environment ExploreContinuous --shuffle --algo ac --coarseness 6 --unconstrained
python main.py --numpy_seed 12 --torch_seed 12 --n_meta_agent_learning_cycles 40 --n_agents_learning_cycles 30 --actor_lr 0.0015 --meta_lr 0.003 --thresholds 15 15 15 --environment ExploreContinuous --shuffle --algo ac --coarseness 6 --unconstrained
python main.py --numpy_seed 13 --torch_seed 13 --n_meta_agent_learning_cycles 40 --n_agents_learning_cycles 30 --actor_lr 0.0015 --meta_lr 0.003 --thresholds 15 15 15 --environment ExploreContinuous --shuffle --algo ac --coarseness 6 --unconstrained
python main.py --numpy_seed 14 --torch_seed 14 --n_meta_agent_learning_cycles 40 --n_agents_learning_cycles 30 --actor_lr 0.0015 --meta_lr 0.003 --thresholds 15 15 15 --environment ExploreContinuous --shuffle --algo ac --coarseness 6 --unconstrained
python main.py --numpy_seed 15 --torch_seed 15 --n_meta_agent_learning_cycles 40 --n_agents_learning_cycles 30 --actor_lr 0.0015 --meta_lr 0.003 --thresholds 15 15 15 --environment ExploreContinuous --shuffle --algo ac --coarseness 6 --unconstrained
python main.py --numpy_seed 16 --torch_seed 16 --n_meta_agent_learning_cycles 40 --n_agents_learning_cycles 30 --actor_lr 0.0015 --meta_lr 0.003 --thresholds 15 15 15 --environment ExploreContinuous --shuffle --algo ac --coarseness 6 --unconstrained
python main.py --numpy_seed 17 --torch_seed 17 --n_meta_agent_learning_cycles 40 --n_agents_learning_cycles 30 --actor_lr 0.0015 --meta_lr 0.003 --thresholds 15 15 15 --environment ExploreContinuous --shuffle --algo ac --coarseness 6 --unconstrained
python main.py --numpy_seed 18 --torch_seed 18 --n_meta_agent_learning_cycles 40 --n_agents_learning_cycles 30 --actor_lr 0.0015 --meta_lr 0.003 --thresholds 15 15 15 --environment ExploreContinuous --shuffle --algo ac --coarseness 6 --unconstrained
python main.py --numpy_seed 19 --torch_seed 19 --n_meta_agent_learning_cycles 40 --n_agents_learning_cycles 30 --actor_lr 0.0015 --meta_lr 0.003 --thresholds 15 15 15 --environment ExploreContinuous --shuffle --algo ac --coarseness 6 --unconstrained
